basePath: /
definitions:
  engine.Field:
    properties:
      adjMines:
        description: count of adjacent mines
        type: integer
      clicked:
        description: indicated whether the field was clicked
        type: boolean
      flagged:
        description: red flag in the field
        type: boolean
      position:
        $ref: '#/definitions/engine.Position'
        description: position in the minefield
        type: object
    type: object
  engine.Game:
    properties:
      cols:
        type: integer
      createdAt:
        type: string
      finishedAt:
        type: string
      id:
        type: string
      mineField:
        items:
          items:
            $ref: '#/definitions/engine.Field'
          type: array
        type: array
      mines:
        type: integer
      rows:
        type: integer
      startedAt:
        type: string
      status:
        type: string
    type: object
  engine.Position:
    properties:
      col:
        description: col of the field position
        type: integer
      row:
        description: row of the field position
        type: integer
    type: object
  responses.ResponseError:
    properties:
      code:
        type: integer
      details:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: cmelgarejo.dev@gmail.com
    name: Christian Melgarejo
  description: A minesweeper game API
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Minesweeper API
  version: 1.0.8
paths:
  /api/game:
    post:
      consumes:
      - application/json
      description: Creates a game of minesweeper and returns a gameID
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/engine.Game'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ResponseError'
      summary: Creates a game of minesweeper
      tags:
      - game
  /api/game/{id}:
    get:
      consumes:
      - application/json
      description: Gets the information of a minesweeper game, fields and users
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/engine.Game'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ResponseError'
      summary: Gets the information of a minesweeper game
      tags:
      - game
    put:
      consumes:
      - application/json
      description: Updates a game of minesweeper and returns a gameID
      parameters:
      - description: Game ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/engine.Game'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ResponseError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ResponseError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ResponseError'
      summary: Updates a game of minesweeper
      tags:
      - game
swagger: "2.0"
